# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10XYbA9oFnEjGFXcHd5j-ItB4CMU8Sf9O
"""

import streamlit as st
import pandas as pd
import datetime

st.title("📅 Excel Date Checker")

uploaded_files = st.file_uploader("Upload Excel files", type=["xlsx"], accept_multiple_files=True)

if uploaded_files:
    today = pd.to_datetime(datetime.date.today()).normalize()
    matched_files = []

    for file in uploaded_files:
        try:
            df = pd.read_excel(file, engine="openpyxl")
            if df.empty:
                continue
            last_row = df.iloc[-1]
            # Try parsing the last column as date
            last_value = last_row.iloc[0]
            parsed_date = pd.to_datetime(last_value, errors='coerce')

            if pd.notna(parsed_date) and parsed_date.normalize() == today:
                matched_files.append(file.name)
        except Exception as e:
            st.error(f"Error processing {file.name}: {e}")

    if matched_files:
        st.success("🎯 These files have today's date in the last row:")
        for name in matched_files:
            st.write(f"✅ {name}")
    else:
        st.warning("❌ No file has today's date in the last row.")



